### PR TITLE
Final submission

### PR DESCRIPTION
**Pull request by BasilCurrie11**
Final submission. Deleted yarn.lock and package-lock.json.

### CODE REVIEW

**Comment by nicoarellano** [comment]
Basil, can you sync, pull and push again please

**Comment by BasilCurrie11** [comment]
I synced, but I can't create another pull request, only view the one I last created. Also, one of the images appears to be missing when I view the page on Brightspace.

**Comment by cimslab** [comment]
There was a typo, you had Map.png and you were looking for map.png (Capitalization is very important in coding)
I fixed it for you

**Comment by BasilCurrie11** [comment]
That's strange, it was working when I tested it with live server. Thanks for fixing it, and I'll keep that in mind

**Pull request closed without merging**
